### ISSUE TITLE
Where is "round/sound1.mp3"?

### ISSUE THREAD

**Issue by PituC** [SunRed/gmod-endroundmusic#2]
Hello, I don't find that folder. I'm new at this. Just tell me how to add custom sounds because i don't know where is that directory.

**Comment by SunRed** [comment]
These are just examples and these sounds are not included, maybe I should comment them out.
I see that the linked image showing the sounds.txt configuration isn't available anymore. I will update the Readme.

To add sounds you cann either edit the existing sounds.txt in the addon's /data/ folder or create a new one in the /data/ directory of your gmod server's root directory (But you would have to delete the data folder from the addon first).

An Example sounds.txt could be like this (Note, this is just normal Lua):

``` Lua
-- Format is like this, whereby EVENT is either INNOCENT, TRAITOR or TIMEOUT
-- WST:AddSound(EVENT, "path relative to "garrysmod/sound", "Artist's name", "Song name")
WST:AddSound(INNOCENT, "path/to/your/sound/file.mp3", "ARTIST", "SONGNAME")
WST:AddSound(INNOCENT, "another/path/but/not/box/shown.mp3") -- box won't be shown for this one, because no artist or song name given
WST:AddSound(TRAITOR, "round/myawesomesong.mp3", "Awesome song's artist", "Awesome song")
WST:AddSound(TIMEOUT, "music/HL2_intro.mp3", "Valve", "Half-Life 2 Intro Music")
-- and so on and so on
```

If you add more than one sound to an event, then a sound will be randomly chosen.

**Comment by PituC** [comment]
Thanks SunRed for this amazing addon!

It works great!. I just created a new folder called "sound" in "garrysmod", then i moved the sounds to that folder and i edited  "sound.txt".
